name: sharded_ckpt test
max_restarts: 0
searcher:
  name: single
  metric: irrelevant
  max_length: 1
resources:
  slots_per_trial: 4
entrypoint: python -m determined.launch.torch_distributed python3 main.py
