name: hf_accelerate_test
entrypoint: python3 accelerate_launch.py --mixed_precision no -- python3 main.py
searcher:
  name: single
  metric: loss
  max_length: 100 # Epochs
resources:
  slots_per_trial: 3
hyperparameters:
  dimension: 16
  batch_size: 10
  num_records: 1000
  lr: 1e-3
  gradient_accumulation_steps: 4
  metric_report_freq: 1
  checkpoint_freq: 20
max_restarts: 0
    
