from typing import Any, Callable, Dict, List, Optional
import warnings

import torch
import torch.distributed as dist
import torch.nn as nn
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.utils.data import Dataset, DataLoader, SequentialSampler, RandomSampler
from torch.utils.data.distributed import DistributedSampler
import torchmetrics

import data

MAX_EXP_ARG = 88.0


class EnsembleStrategy:
    """Small class for storing the build and probability function for an ensemble strategy.
    The pred_fn takes in the vectorized model logits, with the model dimension last, and returns
    the prediction generated by the entire ensemble.
    """

    def __init__(self, build: Callable, pred_fn: Callable) -> None:
        self.build = build
        self.pred_fn = pred_fn


class EnsembleTrainer(nn.Module):
    def __init__(
        self,
        core_context,
        model_list: List[nn.Module],
        train_batch_size: int,
        val_batch_size: int,
        dataset_name: str,
        ensemble_strategy: str = "naive",
        ensemble_args: Optional[dict] = None,
        extra_val_log_metrics: Dict[str, Any] = None,
        sanity_check: bool = False,
        num_combinations: Optional[int] = None,
    ) -> None:
        super().__init__()
        self.core_context = core_context
        self.models = nn.ModuleList(model_list)
        self.models.eval()
        self.train_batch_size = train_batch_size
        self.val_batch_size = val_batch_size
        self.dataset_name = dataset_name
        self.ensemble_strategy = ensemble_strategy
        self.ensemble_args = ensemble_args or {}
        self.extra_val_log_metrics = extra_val_log_metrics or {}
        self.sanity_check = sanity_check
        if self.sanity_check:
            print(f"Running in sanity check mode!")
        self.num_combinations = num_combinations

        self.rank = core_context.distributed.rank
        self.is_distributed = core_context.distributed.size > 1
        self.is_chief = self.rank == 0
        self.device = f"cuda:{self.rank}"
        # Move, freeze, and eval, all models.
        self.models.to(self.device)
        for param in self.models.parameters():
            param.requires_grad = False
        self.models.eval()
        if self.is_distributed:
            dist.init_process_group("nccl")
            self.models = DDP(self.models, device_ids=[self.rank])

        # Mark which strategies require training:
        requires_training_strategies = {"vbmc"}
        self.requires_training = self.ensemble_strategy in requires_training_strategies

        if self.requires_training:
            print(f"Building train_dataset")
            train_dataset = data.get_dataset(name=self.dataset_name, split="train")
        else:
            print(f"Skipping building train_dataset")
            self.train_dataset = None

        print(f"Building val_dataset")
        self.val_dataset = data.get_dataset(name=self.dataset_name, split="val")

        self.trained_batches = 0
        self.train_loader = self.build_train_loader()
        self.val_loader = self.build_val_loader()
        self.criterion = nn.NLLLoss(reduction="none")
        self.optimizer = torch.optim.Adam(self.models.parameters(), lr=0.001)

        self._ensemble_strategies = {
            "naive": EnsembleStrategy(self._build_naive, self._naive_pred_fn),
            "naive_logits": EnsembleStrategy(self._build_naive_logits, self._naive_logits_pred_fn),
            "most_confident": EnsembleStrategy(
                self._build_most_confident, self._most_confident_pred_fn
            ),
            "majority_vote": EnsembleStrategy(
                self._build_majority_vote, self._majority_vote_pred_fn
            ),
        }

        # There can be multiple notions of weights for different ensemble strategies..
        self._ensemble_weights = None
        self._model_weights = None
        # Others need log-likelihoods at intermediate steps.
        self._log_likelihoods = None

        # For some strategies, we will output predictions, rather than probabilities, which changes
        # the trackable metrics.
        no_prob_strategies = {"majority_vote"}
        self.no_prob_strategy = self.ensemble_strategy in no_prob_strategies

        if self.no_prob_strategy:
            self.accuracy_metrics = {"top1_acc": torchmetrics.Accuracy()}
        else:
            self.accuracy_metrics = {
                f"top{k}_acc": torchmetrics.Accuracy(top_k=k) for k in range(1, 11)
            }
        for met in self.accuracy_metrics.values():
            met.to(self.device)

        if self.no_prob_strategy:
            self.loss_metric = None
        else:
            self.loss_metric = torchmetrics.MeanMetric()
            self.loss_metric.to(self.device)

    def build_train_loader(self) -> DataLoader:
        # Not every ensembling strategy needs a train loader
        if self.train_dataset is None:
            return
        if self.is_distributed:
            sampler = DistributedSampler(self.train_dataset, shuffle=True)
        else:
            sampler = RandomSampler(self.train_dataset)
        loader = DataLoader(
            self.train_dataset, batch_size=self.train_batch_size, sampler=sampler, drop_last=True
        )
        return loader

    def build_val_loader(self) -> DataLoader:
        if self.is_distributed:
            sampler = DistributedSampler(self.val_dataset, shuffle=False)
        else:
            sampler = SequentialSampler(self.val_dataset)
        loader = DataLoader(
            self.val_dataset, batch_size=self.val_batch_size, sampler=sampler, drop_last=True
        )
        return loader

    def build_ensemble(self) -> None:
        self._ensemble_strategies[self.ensemble_strategy].build(*self.ensemble_args)

    def forward(self, inputs: torch.Tensor) -> torch.Tensor:
        """Returns logits for the models, stacked along the last dimension."""
        model_logits = torch.stack([model(inputs) for model in self.models], dim=-1)
        return model_logits

    def get_ensembled_preds(self, inputs: torch.Tensor) -> torch.Tensor:
        """Returns predictions for the ensembled model."""
        logits = self(inputs)
        ensembled_preds = self._ensemble_strategies[self.ensemble_strategy].pred_fn(logits)
        if not self.no_prob_strategy and self.sanity_check:
            prob_sum_check = ensembled_preds.sum(dim=1)
            torch.testing.assert_close(prob_sum_check, torch.ones_like(prob_sum_check))
        return ensembled_preds

    def validate_ensemble(self) -> None:
        self.models.eval()
        with torch.no_grad():
            for batch_idx, batch in enumerate(self.val_loader):
                inputs, labels = batch
                inputs, labels = inputs.to(self.device), labels.to(self.device)
                probs = self.get_ensembled_preds(inputs)
                self.update_metrics(probs, labels)
            if self.is_chief:
                computed_metrics = self.compute_metrics("val_")
                conflicted_keys = set(self.extra_val_log_metrics) & set(computed_metrics)
                if conflicted_keys:
                    raise ValueError(
                        f"extra_val_log_metrics/val_metrics conflicting keys: {conflicted_keys}"
                    )
                # Join with extra_val_log_metrics and remove any None-valued metrics with a
                # warning (these would throw errors).
                reported_metrics = {**self.extra_val_log_metrics, **computed_metrics}
                for key in list(reported_metrics):
                    if reported_metrics[key] is None:
                        warnings.warn(f"Removing val metric {key} whose value is None.")
                        reported_metrics.pop(key)

                self.core_context.train.report_validation_metrics(
                    steps_completed=self.trained_batches, metrics=reported_metrics
                )
            self.reset_metrics()
        if self.core_context.preempt.should_preempt():
            return

    def update_metrics(self, probs, labels) -> None:
        for met in self.accuracy_metrics.values():
            met(probs, labels)
        if self.loss_metric is not None:
            # NLLLoss expects log-probabilities
            loss = self.criterion(probs.log(), labels)
            self.loss_metric(loss)

    def compute_metrics(self, prefix: str = ""):
        computed_metrics = {
            prefix + name: metric.compute().item() for name, metric in self.accuracy_metrics.items()
        }
        if self.loss_metric is not None:
            computed_metrics[prefix + "loss"] = self.loss_metric.compute().item()
        return computed_metrics

    def reset_metrics(self):
        for met in self.accuracy_metrics.values():
            met.reset()
        if self.loss_metric is not None:
            self.loss_metric.reset()

    def _build_naive(self) -> None:
        """Average the probabilities of all models with equal weights."""
        num_models = len(self.models)
        self._ensemble_weights = torch.ones(num_models, device=self.device) / num_models

    def _naive_pred_fn(self, logits: torch.Tensor) -> torch.Tensor:
        model_probs = logits.softmax(dim=1)
        ensemble_prob = model_probs @ self._ensemble_weights
        return ensemble_prob

    def _build_naive_logits(self) -> None:
        """Average the logits of all models with equal weights."""
        num_models = len(self.models)
        self._ensemble_weights = torch.ones(num_models, device=self.device) / num_models

    def _naive_logits_pred_fn(self, logits: torch.Tensor) -> torch.Tensor:
        ensemble_logits = logits @ self._ensemble_weights
        ensemble_prob = ensemble_logits.softmax(dim=1)
        return ensemble_prob

    def _build_most_confident(self) -> None:
        """For each sample, use the prediction of the most-confident model."""
        pass

    def _most_confident_pred_fn(self, logits: torch.Tensor) -> torch.Tensor:
        ensembles_probs = logits.softmax(dim=1)
        max_idxs = ensembles_probs.max(dim=1).values.argmax(dim=-1)
        ensemble_prob = ensembles_probs[torch.arange(len(max_idxs)), ..., max_idxs]
        return ensemble_prob

    def _build_majority_vote(self) -> None:
        """For each sample, use a majority vote among models. Torch breaks ties by choosing the
        lowest prediction index among tied values.
        """
        pass

    def _majority_vote_pred_fn(self, logits: torch.Tensor) -> torch.Tensor:
        ensembles_preds = logits.argmax(dim=1)
        majority_vote_preds = ensembles_preds.mode(-1).values
        return majority_vote_preds

    def _build_vbmc(self) -> None:
        """For each sample, use a majority vote among models. Torch breaks ties by choosing the
        lowest prediction index among tied values.
        """
        # Generate num_combinations sets of model combinations. We use a flat prior over this discrete set.
        dirichlet = torch.distributions.dirichlet.Dirichlet(torch.ones(len(self.models)))
        self._model_weights = dirichlet.sample((self.num_combinations,)).to(self.device).T
        self._train_vbmc()

    def _vbmc_pred_fn(self, logits: torch.Tensor) -> torch.Tensor:
        model_probs = logits.softmax(dim=1)
        ensemble_prob = model_probs @ self._ensemble_weights
        return ensemble_prob

    def _train_vbmc(self) -> None:
        with torch.no_grad():
            self._log_likelihoods = torch.zeros(self.num_combinations, device=self.device)
            vbmc_criterion = nn.NLLLoss(reduction="none")
            for batch_idx, batch in enumerate(self.train_loader):
                inputs, labels = batch
                inputs, labels = inputs.to(self.device), labels.to(self.device)
                logits = self(inputs)
                probs = logits.softmax(dim=1)
                log_probs = probs.log()
                labels = labels[..., None]
                labels = labels.expand(-1, self.num_combinations)
                loss = vbmc_criterion(log_probs, labels).sum(dim=0)
                # Subtract loss to get *positive* log-likelihood sum.
                self._log_likelihoods -= loss
                self.trained_batches += 1

            # Prevent overflow for the summed log-likelihoods
            self._log_likelihoods -= self._log_likelihoods.mean()
            overflow_diff = self._log_likelihoods.max() - MAX_EXP_ARG
            if overflow_diff > 0:
                self._log_likelihoods -= overflow_diff
        posterior = self._log_likelihoods.softmax(dim=0)
        self._ensemble_weights = self._model_weights @ posterior
        reported_metrics = {
            "posterior": [p.item() for p in posterior],
            "ensemble_weights": [w.item() for w in self._ensemble_weights],
        }
        self.core_context.train.report_training_metrics(
            steps_completed=self.trained_batches, metrics=reported_metrics
        )
        if self.core_context.preempt.should_preempt():
            return
