name: mobilenet_v3_small_imagenet_distributed
entrypoint: model_def:ModelTrial
reproducibility:
  experiment_seed: 42
data:
  dataset_name: imagenet
  # TODO: Change this to the name of your bucket.
  gcs_bucket: determined-ai-datasets
  # TODO: Path to files inside the above bucket that contain newline separated list of all image blob paths.
  # Generate using generate_blob_list.py
  gcs_train_blob_list_path: imagenet/imagenet/train-blob-list.txt
  gcs_validation_blob_list_path: imagenet/imagenet/validation-blob-list.txt
  num_workers: 4
  pin_memory: True
  persistent_workers: True
records_per_epoch:
  1281167
hyperparameters:
  global_batch_size: 512
  model:
    pretrained: True
  # timm.optim.create_optimizer args
  optimizer:
    opt: adamw
    lr: 1.0e-5
    opt_eps: 1.0e-8
    opt_betas: null
    clip_grad: null
    momentum: 0.9
    weight_decay: 0.05
  # timm.data.create_transform args
  transform:
    scale: [ 0.9, 1.0 ]
    ratio: [ .9, 1.1 ]
    hflip: 0.5
    vflip: 0.
    color_jitter: 0.1
    auto_augment: null
    interpolation: bicubic
    re_prob: 0.1
    re_mode: pixel
    re_count: 1
min_validation_period:
  epochs: 1
searcher:
  name: single
  metric: validation_loss
  max_length:
    epochs: 1
  smaller_is_better: true
max_restarts: 0
resources:
  slots_per_trial: 4
optimizations:
  average_training_metrics: True
perform_initial_validation: True
checkpoint_policy: all