name: download_checkpoint_restore_path_hf_datasets (DS)
max_restarts: 0
searcher:
  name: single
  metric: irrelevant
  max_length: 1
environment:
  environment_variables:
    - NCCL_DEBUG=INFO
    # You may need to modify this to match your network configuration.
    - NCCL_SOCKET_IFNAME=ens,eth,ib
  image:
    gpu: garrettgoon/mh_train
resources:
  slots_per_trial: 2
entrypoint: python -m determined.launch.deepspeed python main.py
