name: basic_cnn_cifar100_single
entrypoint: model_def:ModelTrial
reproducibility:
  experiment_seed: 42
data:
  dataset_name: cifar100
  download_dir: /data
  num_workers: 4
  pin_memory: True
  persistent_workers: True
records_per_epoch:
  50000
hyperparameters:
  global_batch_size: 2048
  model:
    layer1_dropout: .2
    layer2_dropout: .2
    layer3_dropout: .2
  # timm.optim.create_optimizer args
  optimizer:
    opt: adamw
    lr: 1.0e-3
    opt_eps: 1.0e-8
    opt_betas: null
    clip_grad: null
    momentum: 0.9
    weight_decay: 0.05
  # timm.data.create_transform args
  transform:
    scale: [ 0.9, 1.0 ]
    ratio: [ .9, 1.1 ]
    hflip: 0.5
    vflip: 0.
    color_jitter: 0.1
    auto_augment: null
    interpolation: bicubic
    re_prob: 0.1
    re_mode: pixel
    re_count: 1
min_validation_period:
  epochs: 1
min_checkpoint_period:
  epochs: 1
searcher:
  name: single
  metric: validation_loss
  max_length:
    epochs: 32
  smaller_is_better: true
max_restarts: 0
optimizations:
  average_training_metrics: True