name: mnist-custom-search-experiment
max_restarts: 0
data:
  url: https://s3-us-west-2.amazonaws.com/determined-ai-test-data/pytorch_mnist.tar.gz
searcher:
  name: custom
  metric: validation_loss
  smaller_is_better: true
  unit: batches
resources:
  slots_per_trial: 2
  max_slots: 16
environment:
  environment_variables:
    - NCCL_DEBUG=INFO
    # You may need to modify this to match your network configuration.
    - NCCL_SOCKET_IFNAME=ens,eth,ib
  #    - CUDA_LAUNCH_BLOCKING=1
  #    - NCCL_BLOCKING_WAIT=1
  #    - NCCL_IB_DISABLE=1
  image:
    gpu: determinedai/environments:cuda-11.3-pytorch-1.10-tf-2.8-deepspeed-0.7.0-gpu-24586f0
entrypoint:
  - python3
  - -m
  - determined.launch.deepspeed
  - --trial
  - model_def:MNistTrial
