name: download_checkpoint
max_restarts: 0
searcher:
  name: single
  metric: irrelevant
  max_length: 1
resources:
  slots_per_trial: 1
entrypoint: python -m determined.launch.deepspeed python main.py
