name: download_checkpoint_hf_datasets
max_restarts: 0
searcher:
  name: single
  metric: irrelevant
  max_length: 1
resources:
  slots_per_trial: 2
environment:
  image:
    gpu: garrettgoon/mh_train
entrypoint: python -m determined.launch.torch_distributed python main.py
