name: shared fs ckpt test
max_restarts: 0
searcher:
  name: single
  metric: irrelevant
  max_length: 1
resources:
  slots_per_trial: 0
checkpoint_storage:
  type: shared_fs
  host_path: /tmp/det_shared_fs
environment:
  environment_variables:
    - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
entrypoint: python3 main.py
