name: checkpoint_tester
max_restarts: 0
resources:
  slots_per_trial: 1
searcher:
  name: single
  metric: arbitrary_metric_name
  max_length: 1
entrypoint: python -m determined.launch.torch_distributed -- python3 -m double_deletion_test.main
