name: report_from_multiple_ranks
max_restarts: 0
searcher:
  name: single
  metric: irrelevant
  max_length: 1
resources:
  slots_per_trial: 2
entrypoint: python3 -m determined.launch.torch_distributed python3 main.py
