name: list in hps test
max_restarts: 0
searcher:
  name: single
  metric: irrelevant
  max_length: 1
resources:
  slots_per_trial: 0
hyperparameters:
  some_list:
    - 1
    - 2
    - 3
entrypoint: python3 main.py
