name: no_op_test
max_restarts: 0
environment:
  image:
    gpu: garrettgoon/mh_train
    cpu: garrettgoon/mh_train
  force_pull_image: true
searcher:
  name: single
  metric: irrelevant
  max_length: 1
resources:
  slots_per_trial: 1
entrypoint: python3 main.py
