name: cifar10_pytorch_const
workspace: Garrett
project: Tests
max_restarts: 0
hyperparameters:
  global_batch_size: 2
  lr: 1.0e-4
  dim: 1000
  num_train_records: 20
  num_val_records: 20
resources:
  slots_per_trial: 2
searcher:
  name: single
  metric: val_loss
  max_length:
    batches: 10
entrypoint: python3 -m determined.launch.torch_distributed python3 main_dist.py
