entrypoint:
    python -m determined.launch.torch_distributed
    python -m mnist_pytorch_core_api
name: mnist_pytorch_dist
workspace: Core API
project: MNIST
max_restarts: 0
environment:
    environment_variables:
        - OMP_NUM_THREADS=1
resources:
    slots_per_trial: 1
searcher:
    name: single
    max_length: 1
    metric: val_loss
hyperparameters:
    model:
        n_filters1: 32
        n_filters2: 32
        dropout1: 0.25
        dropout2: 0.5
    optimizer:
        lr: 0.001
    trainer:
        worker_train_batch_size: 1024
        worker_val_batch_size: 2048
        train_metric_agg_rate: 8
        epochs: 1
        val_freq: 1