name: test
hyperparameters:
  ds_config:
    optimizer:
      weight_decay: 1.0e-6
      type: const
      val:
        type: Adam
searcher:
  name: single
  metric: arbitrary
  max_length: 1
entrypoint: python3 print_hps.py
