name: huggyllama/llama-13b gradient_checkpointing
workspace: DS_AT_PROTOTYPING
project: hf
debug: false
environment:
  environment_variables:
    - NCCL_DEBUG=INFO
    # You may need to modify this to match your network configuration.
    - NCCL_SOCKET_IFNAME=ens,eth,ib
  image:
    gpu: determinedai/environments:cuda-11.3-pytorch-1.10-deepspeed-0.8.3-gpu-0.21.2
    cpu: determinedai/environments:cuda-11.3-pytorch-1.10-deepspeed-0.8.3-gpu-0.21.2
resources:
  slots_per_trial: 8
searcher:
  name: single
  max_length:
    batches: 1000
  metric: eval_loss
hyperparameters:
  deepspeed_config: ds_configs/ds_config_stage_3.json
  training_arguments:
    learning_rate: 1e-9
entrypoint: >-
  python -m determined.launch.deepspeed
  python run_clm.py
  --model_name_or_path huggyllama/llama-13b
  --dataset_name wikitext
  --dataset_config_name wikitext-2-raw-v1
  --do_train
  --do_eval
  --max_steps 1000
  --logging_strategy steps
  --logging_steps 10
  --output_dir /tmp/test-clm
  --eval_steps 10
  --evaluation_strategy no
  --save_total_limit 3
  --seed 1337
  --save_strategy no
  --save_steps 20
  --deepspeed ds_configs/ds_config_stage_3.json
  --per_device_train_batch_size 1
  --per_device_eval_batch_size 1
  --cache_dir ./garrettgoon/cache_dir
  --trust_remote_code false
  --gradient_checkpointing True
# TODO: Delete the cache_dir field; just using them for fast testing.
max_restarts: 0
