name: keep_three_largest_test
max_restarts: 0
checkpoint_storage:
  save_trial_best: 10
resources:
  slots_per_trial: 1
searcher:
  name: single
  metric: arbitrary_metric_name
  max_length: 1
  smaller_is_better: false
entrypoint: python -m determined.launch.torch_distributed -- python3 -m keep_three_largest_test.main
