name: checkpoint_tester
max_restarts: 0
checkpoint_storage:
  save_trial_best: 3
resources:
  slots_per_trial: 1
searcher:
  name: single
  metric: arbitrary_metric_name
  max_length: 1
  smaller_is_better: false
entrypoint: python -m determined.launch.torch_distributed -- python3 main.py
