name: ds_continue_batch_idx 
debug: false
hyperparameters:
  deepspeed_config: ds_config.json
environment:
    environment_variables:
        - NCCL_DEBUG=INFO
        # You may need to modify this to match your network configuration.
        - NCCL_SOCKET_IFNAME=ens,eth,ib
    #    - CUDA_LAUNCH_BLOCKING=1
    #    - NCCL_BLOCKING_WAIT=1
    #    - NCCL_IB_DISABLE=1
    image:
        gpu: determinedai/environments:cuda-11.3-pytorch-1.10-tf-2.8-deepspeed-0.7.0-gpu-24586f0
bind_mounts:
    - host_path: /tmp
      container_path: /data
    - host_path: /tmp
      container_path: /root/.cache
resources:
  slots_per_trial: 2
searcher:
  name: single
  metric: accuracy
  smaller_is_better: false
  max_length:
    batches: 10 
entrypoint:
  - python3
  - -m
  - determined.launch.deepspeed
  - --trial
  - model_def:BatchIdxTrial
checkpoint_policy: none
max_restarts: 0
scheduling_unit: 1
