name: cifar10_100_batches_10_batch_size
hyperparameters:
  learning_rate: 1.0e-4
  learning_rate_decay: 1.0e-6
  layer1_dropout: 0.25
  layer2_dropout: 0.25
  layer3_dropout: 0.5
  global_batch_size: 10
searcher:
  name: single
  metric: validation_error
  max_length:
    batches: 100
entrypoint: model_def:CIFARTrial
min_validation_period:
  batches: 10
