name: cifar10_50_batches_20_batch_size
hyperparameters:
  learning_rate: 1.0e-4
  learning_rate_decay: 1.0e-6
  layer1_dropout: 0.25
  layer2_dropout: 0.25
  layer3_dropout: 0.5
  global_batch_size: 20
records_per_epoch: 50000
searcher:
  name: single
  metric: validation_error
  max_length:
    batches: 50
entrypoint: model_def:CIFARTrial
min_validation_period:
  batches: 5
