name: step_every_epoch_test
hyperparameters:
  lr: 1.0e-4
  dataset_size: 4
  global_batch_size: 3 # Per-GPU batch size of 32
resources:
  slots_per_trial: 3
records_per_epoch: 4
searcher:
  name: single
  metric: val_loss
  max_length:
    epochs: 100
entrypoint: model_def:StepEveryEpochTrial
min_validation_period:
  epochs: 1000
max_restarts: 0
