name: step_every_epoch_test
hyperparameters:
  lr: 1.0e-4
  dataset_size: 3
  global_batch_size: 2
resources:
  slots_per_trial: 2
searcher:
  name: single
  metric: val_loss
  max_length:
    batches: 100
entrypoint: model_def:StepEveryEpochTrial
min_validation_period:
  batches: 1000
max_restarts: 0
