name: empty_env_vars_test
max_restarts: 0
searcher:
  name: single
  metric: irrelevant
  max_length: 1
resources:
  slots_per_trial: 0
environment:
  environment_variables:
    - EMPTY
    - NOT_EMPTY=test
entrypoint: python3 main.py
